"use client"

import { PageContent } from "@/components/page-content"
import { 
  User, 
  Globe, 
  CheckCircle2, 
  Code,
  Settings,
  Lock,
  XCircle,
  Target,
  Sparkles
} from "lucide-react"
import Link from "next/link"

export default function UserIdClientIdPage() {
  return (
    <PageContent
      title="User-ID vs Client-ID"
      description="Understand the difference between User-ID and Client-ID, and when to use each for accurate user identification and cross-device tracking."
      status="Stable"
    >
      
      {/* Client-ID Section */}
      <div className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="border-animated glass-strong rounded-2xl p-8 hover-glow">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 rounded-lg bg-[#4285F4]/10 border border-[#4285F4]/30 pulse-glow">
              <Globe className="h-6 w-6 text-[#4285F4]" />
            </div>
            <h2 className="font-mono text-2xl font-bold text-[#e8f4f8]">
              Client-ID (Automatic)
            </h2>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            <div className="glass hover-lift rounded-xl p-5 border border-[#4285F4]/20">
              <h3 className="font-mono font-semibold text-[#4285F4] mb-3">What is Client-ID?</h3>
              <p className="text-sm text-[#8b949e] mb-4">
                Anonymous identifier automatically generated by GA4 and stored in browser cookies.
              </p>
              <div className="space-y-2 text-xs text-[#8b949e]">
                <div><span className="font-mono text-[#4285F4]">Format:</span> 14-digit number</div>
                <div><span className="font-mono text-[#4285F4]">Example:</span> 1234567890.1234567890</div>
                <div><span className="font-mono text-[#4285F4]">Stored in:</span> _ga cookie</div>
                <div><span className="font-mono text-[#4285F4]">Generated by:</span> gtag.js automatically</div>
              </div>
            </div>

            <div className="glass hover-lift rounded-xl p-5 border border-[#34A853]/20">
              <h3 className="font-mono font-semibold text-[#34A853] mb-3">Benefits</h3>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#34A853] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Works without user login</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#34A853] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Tracks anonymous visitors</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#34A853] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Cross-session tracking</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#34A853] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Automatic - no code required</span>
                </li>
              </ul>
            </div>

            <div className="glass hover-lift rounded-xl p-5 border border-[#EA4335]/20">
              <h3 className="font-mono font-semibold text-[#EA4335] mb-3">Limitations</h3>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <XCircle className="h-4 w-4 text-[#EA4335] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Not persistent across devices</span>
                </li>
                <li className="flex items-start gap-2">
                  <XCircle className="h-4 w-4 text-[#EA4335] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Lost when cookies cleared</span>
                </li>
                <li className="flex items-start gap-2">
                  <XCircle className="h-4 w-4 text-[#EA4335] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Lost when browser changes</span>
                </li>
                <li className="flex items-start gap-2">
                  <XCircle className="h-4 w-4 text-[#EA4335] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Cannot identify actual user</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* User-ID Section */}
      <div className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700 delay-100">
        <div className="border-animated glass-strong rounded-2xl p-8 hover-glow">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 rounded-lg bg-[#34A853]/10 border border-[#34A853]/30 pulse-glow">
              <User className="h-6 w-6 text-[#34A853]" />
            </div>
            <h2 className="font-mono text-2xl font-bold text-[#e8f4f8]">
              User-ID (Manual)
            </h2>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            <div className="glass hover-lift rounded-xl p-5 border border-[#34A853]/20">
              <h3 className="font-mono font-semibold text-[#34A853] mb-3">What is User-ID?</h3>
              <p className="text-sm text-[#8b949e] mb-4">
                Persistent identifier for logged-in users. Links user across all devices and sessions.
              </p>
              <div className="space-y-2 text-xs text-[#8b949e]">
                <div><span className="font-mono text-[#34A853]">Format:</span> String (your user ID)</div>
                <div><span className="font-mono text-[#34A853]">Example:</span> user_1234567890</div>
                <div><span className="font-mono text-[#34A853]">Set by:</span> You (in code)</div>
                <div><span className="font-mono text-[#34A853]">Stored in:</span> User scope</div>
              </div>
            </div>

            <div className="glass hover-lift rounded-xl p-5 border border-[#4285F4]/20">
              <h3 className="font-mono font-semibold text-[#4285F4] mb-3">Benefits</h3>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#4285F4] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Cross-device tracking</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#4285F4] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Persistent across sessions</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#4285F4] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Accurate user lifetime value</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="h-4 w-4 text-[#4285F4] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Better attribution</span>
                </li>
              </ul>
            </div>

            <div className="glass hover-lift rounded-xl p-5 border border-[#FF6D00]/20">
              <h3 className="font-mono font-semibold text-[#FF6D00] mb-3">Requirements</h3>
              <ul className="space-y-2">
                <li className="flex items-start gap-2">
                  <Lock className="h-4 w-4 text-[#FF6D00] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">User must be logged in</span>
                </li>
                <li className="flex items-start gap-2">
                  <Lock className="h-4 w-4 text-[#FF6D00] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">User must consent</span>
                </li>
                <li className="flex items-start gap-2">
                  <Lock className="h-4 w-4 text-[#FF6D00] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">User ID must be unique</span>
                </li>
                <li className="flex items-start gap-2">
                  <Lock className="h-4 w-4 text-[#FF6D00] mt-0.5 flex-shrink-0" />
                  <span className="text-sm text-[#8b949e]">Privacy regulations</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* Implementation */}
      <div className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700 delay-200">
        <div className="flex items-center gap-3 mb-8">
          <div className="h-1 w-12 bg-gradient-to-r from-[#FF6D00] to-[#4285F4] rounded-full"></div>
          <h2 className="font-mono text-2xl font-bold text-[#e8f4f8]">
            Setting User-ID
          </h2>
          <div className="h-1 flex-1 bg-gradient-to-r from-[#4285F4] to-transparent rounded-full"></div>
        </div>

        <div className="space-y-6">
          <div className="border-animated glass-strong rounded-2xl p-6 hover-glow">
            <h3 className="font-mono font-semibold text-[#e8f4f8] mb-3">When User Logs In</h3>
            <div className="code-block">
              <pre className="text-sm font-mono text-[#FF6D00] overflow-x-auto">
{`// Set User-ID after successful login
const userId = 'user_' + userDatabaseId

// Set in GA4
gtag('config', 'G-XXXXXXXXXX', {
  user_id: userId
})

// Or update for existing session
gtag('set', 'user_properties', {
  user_id: userId,
  login_status: 'logged_in'
})`}
              </pre>
            </div>
          </div>

          <div className="border-animated glass-strong rounded-2xl p-6 hover-glow">
            <h3 className="font-mono font-semibold text-[#e8f4f8] mb-3">On Logout</h3>
            <div className="code-block">
              <pre className="text-sm font-mono text-[#34A853] overflow-x-auto">
{`// Clear User-ID on logout
gtag('config', 'G-XXXXXXXXXX', {
  user_id: null
})

// Update user property
gtag('set', 'user_properties', {
  login_status: 'logged_out'
})`}
              </pre>
            </div>
          </div>

          <div className="border-animated glass-strong rounded-2xl p-6 hover-glow">
            <h3 className="font-mono font-semibold text-[#e8f4f8] mb-3">Server-Side (Measurement Protocol)</h3>
            <div className="code-block">
              <pre className="text-sm font-mono text-[#4285F4] overflow-x-auto">
{`// Include user_id in server request
{
  "client_id": "1234567890.1234567890",
  "user_id": "user_1234567890",
  "events": [{
    "name": "purchase",
    "params": {
      "transaction_id": "T_12345",
      "value": 99.99,
      "currency": "USD"
    }
  }]
}`}
              </pre>
            </div>
          </div>
        </div>
      </div>

      {/* Comparison Table */}
      <div className="mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700 delay-300">
        <div className="glass-strong rounded-2xl p-8 border border-[#FF6D00]/20">
          <div className="flex items-center gap-3 mb-6">
            <Sparkles className="h-6 w-6 text-[#FF6D00] animate-pulse" />
            <h2 className="font-mono text-2xl font-bold text-[#e8f4f8]">
              When to Use Each
            </h2>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-[#FF6D00]/20">
                  <th className="font-mono text-left text-[#e8f4f8] py-3 px-4">Use Case</th>
                  <th className="font-mono text-left text-[#4285F4] py-3 px-4">Client-ID</th>
                  <th className="font-mono text-left text-[#34A853] py-3 px-4">User-ID</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-[#FF6D00]/10">
                  <td className="py-3 px-4 font-mono text-[#e8f4f8]">Anonymous Visitors</td>
                  <td className="py-3 px-4 text-[#34A853]">✓ Use</td>
                  <td className="py-3 px-4 text-[#EA4335]">✗ Not Available</td>
                </tr>
                <tr className="border-b border-[#FF6D00]/10">
                  <td className="py-3 px-4 font-mono text-[#e8f4f8]">Logged-In Users</td>
                  <td className="py-3 px-4 text-[#34A853]">✓ Use</td>
                  <td className="py-3 px-4 text-[#34A853]">✓ Use</td>
                </tr>
                <tr className="border-b border-[#FF6D00]/10">
                  <td className="py-3 px-4 font-mono text-[#e8f4f8]">Cross-Device Tracking</td>
                  <td className="py-3 px-4 text-[#EA4335]">✗ Not Possible</td>
                  <td className="py-3 px-4 text-[#34A853]">✓ Use</td>
                </tr>
                <tr className="border-b border-[#FF6D00]/10">
                  <td className="py-3 px-4 font-mono text-[#e8f4f8]">User Lifetime Value</td>
                  <td className="py-3 px-4 text-[#EA4335]">✗ Not Accurate</td>
                  <td className="py-3 px-4 text-[#34A853]">✓ Accurate</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 font-mono text-[#e8f4f8]">Setup Complexity</td>
                  <td className="py-3 px-4 text-[#34A853]">None (automatic)</td>
                  <td className="py-3 px-4 text-[#FF6D00]">Medium (requires auth)</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </PageContent>
  )
}
